import { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, CalendarClock, Check, ChevronLeft, ChevronRight, CircleDollarSign,
  Cloud, ExternalLink, Filter, KeyRound, RefreshCw, Rocket, Save, Search, Settings2,
  ShieldCheck, ShieldOff, Sparkles, Store, X,
} from 'lucide-react';
import api from '../../services/api';
import PageHeader from '../../components/admin/PageHeader';
import PageState from '../../components/ui/PageState';
import { useAuth } from '../../context/AuthContext';

const RELEASE_EMPTY = { version: '', channel: 'stable', notes: '', mandatory: false, eligibleIndustries: [] };
const TABS = ['Overview', 'Subscription', 'Features & limits', 'Deployment', 'Activity'];

export default function ClientInstallations() {
  const { notify } = useAuth();
  const [workspace, setWorkspace] = useState(null);
  const [query, setQuery] = useState({ q: '', status: '', plan: '', industry: '', attention: '', page: 1 });
  const [release, setRelease] = useState(RELEASE_EMPTY);
  const [busy, setBusy] = useState({});
  const [error, setError] = useState('');
  const [selected, setSelected] = useState(null);
  const [operations, setOperations] = useState(null);
  const [edit, setEdit] = useState(null);
  const [tab, setTab] = useState('Overview');
  const [danger, setDanger] = useState(null);

  const load = async (next = query) => {
    const params = new URLSearchParams(Object.entries(next).filter(([, value]) => value !== '' && value != null));
    setError('');
    try { setWorkspace(await api.get(`/master/clients?${params}`)); }
    catch (requestError) { if (!workspace) setError(requestError.message); else notify(requestError.message, 'error', 'Client control'); }
  };
  useEffect(() => { const timer = setTimeout(() => load(query), query.q ? 300 : 0); return () => clearTimeout(timer); }, [query.q, query.status, query.plan, query.industry, query.attention, query.page]); // eslint-disable-line react-hooks/exhaustive-deps

  const run = async (key, task) => {
    if (busy[key]) return;
    setBusy((current) => ({ ...current, [key]: true }));
    try { await task(); } catch (requestError) { notify(requestError.message, 'error', 'Client control'); }
    finally { setBusy((current) => ({ ...current, [key]: false })); }
  };
  const openClient = (item) => run(`open-${item.id}`, async () => {
    setSelected(item.id); setOperations(null); setEdit(toEdit(item)); setTab('Overview');
    const result = await api.get(`/master/installations/${item.id}/operations`);
    setOperations(result); setEdit(toEdit(result.installation));
  });
  const closeClient = () => { setSelected(null); setOperations(null); setEdit(null); setDanger(null); };
  const mergeInstallation = (item) => {
    setWorkspace((current) => current ? { ...current, installations: current.installations.map((row) => row.id === item.id ? item : row) } : current);
    setOperations((current) => current ? { ...current, installation: item } : current);
    setEdit(toEdit(item));
  };
  const save = (extra = {}, message = 'Client settings have been updated.') => run(`save-${selected}`, async () => {
    const payload = { ...edit, ...extra };
    if (payload.deployHookUrl === '') delete payload.deployHookUrl;
    if (payload.deployHookUrl === '__REMOVE__') payload.deployHookUrl = '';
    const result = await api.patch(`/master/installations/${selected}`, payload);
    mergeInstallation(result.installation); notify(message, 'success', 'Client saved');
  });
  const grant = (value) => save({ grant: value, ...(value === 'TRIAL' ? { grantDays: 30 } : {}) }, `${grantLabel(value)} access is now active for this client.`);
  const publishRelease = () => run('release', async () => {
    await api.post('/master/releases', release); setRelease(RELEASE_EMPTY); await load(query);
    notify('The tested release can now be assigned to eligible clients.', 'success', 'Release published');
  });
  const rotateKey = () => run(`key-${selected}`, async () => {
    const result = await api.post(`/master/installations/${selected}/rotate-key`, {});
    const blob = new Blob([`${JSON.stringify({ notice: result.notice, ...result.credentials }, null, 2)}\n`], { type: 'application/json' });
    const url = URL.createObjectURL(blob); const link = document.createElement('a');
    link.href = url; link.download = `${operations.installation.projectSlug}-installation-key.json`; link.click();
    window.setTimeout(() => URL.revokeObjectURL(url), 1000);
    notify('The old key is disabled. Apply the downloaded key to this client backend.', 'warning', 'Key rotated');
  });
  const deploy = () => run(`deploy-${selected}`, async () => {
    const result = await api.post(`/master/installations/${selected}/deploy`, {});
    mergeInstallation(result.installation);
    notify('The provider accepted the request. Live status appears after the target version checks in.', 'success', 'Deployment started');
  });

  const industries = workspace?.industryOptions || [];
  const plans = workspace?.plans || [];
  const installation = operations?.installation;
  const published = workspace?.releases?.filter((item) => item.status === 'PUBLISHED') || [];
  const eligibleReleases = installation ? published.filter((item) => item.channel === edit?.updateChannel && (!item.eligibleIndustries?.length || item.eligibleIndustries.includes(installation.industry))) : [];
  const allFeatures = useMemo(() => [...new Set((workspace?.plans || []).flatMap((plan) => plan.features || []))], [workspace?.plans]);

  if (!workspace && error) return <PageState error={error} onRetry={() => load(query)} />;
  if (!workspace) return <PageState loading loadingLabel="Loading client operations..." />;

  return <section className="min-w-0 space-y-5">
    <PageHeader title="Client control" note="Subscriptions, usage, releases and service health for every isolated client.">
      <button type="button" className="admin-btn-ghost" onClick={() => load(query)}><RefreshCw size={16} /> Refresh</button>
    </PageHeader>
    {!workspace.controlPlane?.signingReady && <Notice icon={AlertTriangle} title="Licence signing is not ready">Set the platform signing keys before issuing production client packages.</Notice>}

    <div className="grid grid-cols-2 gap-3 xl:grid-cols-6">
      <Summary icon={Store} label="All clients" value={workspace.summary.total} />
      <Summary icon={ShieldCheck} label="Active" value={workspace.summary.active} tone="green" />
      <Summary icon={Sparkles} label="Free trials" value={workspace.summary.trials} />
      <Summary icon={CalendarClock} label="Expiring in 30d" value={workspace.summary.expiring} tone={workspace.summary.expiring ? 'amber' : ''} onClick={() => setQuery((q) => ({ ...q, attention: 'expiring', page: 1 }))} />
      <Summary icon={Cloud} label="Offline 24h+" value={workspace.summary.offline} tone={workspace.summary.offline ? 'red' : ''} onClick={() => setQuery((q) => ({ ...q, attention: 'offline', page: 1 }))} />
      <Summary icon={CircleDollarSign} label="Paid this month" value={`₹${Number(workspace.summary.monthlyRevenue || 0).toLocaleString('en-IN')}`} />
    </div>

    <ReleaseManager workspace={workspace} release={release} setRelease={setRelease} busy={busy.release} onPublish={publishRelease} />

    <div className="admin-card p-4">
      <div className="grid gap-3 lg:grid-cols-[minmax(260px,1fr)_repeat(4,minmax(130px,auto))]">
        <label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17} /><input aria-label="Search clients" value={query.q} onChange={(event) => setQuery({ ...query, q: event.target.value, page: 1 })} className="h-11 w-full rounded-xl border pl-10 pr-3 text-sm" placeholder="Search company, phone, email, domain or ID" /></label>
        <FilterSelect label="Status" value={query.status} onChange={(status) => setQuery({ ...query, status, page: 1 })}>{['TRIAL', 'ACTIVE', 'EXPIRED', 'SUSPENDED', 'REVOKED'].map((value) => <option key={value}>{value}</option>)}</FilterSelect>
        <FilterSelect label="Plan" value={query.plan} onChange={(plan) => setQuery({ ...query, plan, page: 1 })}>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</FilterSelect>
        <FilterSelect label="Industry" value={query.industry} onChange={(industry) => setQuery({ ...query, industry, page: 1 })}>{industries.map((item) => <option key={item.industry} value={item.industry}>{item.name}</option>)}</FilterSelect>
        <FilterSelect label="Attention" value={query.attention} onChange={(attention) => setQuery({ ...query, attention, page: 1 })}><option value="expiring">Expiring soon</option><option value="offline">Offline</option><option value="updates">Update pending</option></FilterSelect>
      </div>
      {(query.status || query.plan || query.industry || query.attention || query.q) && <button type="button" className="mt-3 text-xs font-black text-[#8f2748]" onClick={() => setQuery({ q: '', status: '', plan: '', industry: '', attention: '', page: 1 })}>Clear all filters</button>}
    </div>

    {workspace.installations.length ? <>
      <div className="hidden overflow-hidden rounded-2xl border bg-white shadow-sm md:block"><table className="w-full text-left text-sm"><thead className="bg-[#fffaf7] text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="p-4">Client</th><th>Access</th><th>Usage</th><th>Health</th><th>Version</th><th className="pr-4 text-right">Action</th></tr></thead><tbody>{workspace.installations.map((item) => <ClientRow key={item.id} item={item} onOpen={() => openClient(item)} busy={busy[`open-${item.id}`]} />)}</tbody></table></div>
      <div className="grid gap-3 md:hidden">{workspace.installations.map((item) => <ClientCard key={item.id} item={item} onOpen={() => openClient(item)} />)}</div>
      <Pagination value={workspace.pagination} onChange={(page) => setQuery({ ...query, page })} />
    </> : <PageState empty emptyTitle="No clients match these filters" emptyMessage="Clear filters or generate a new isolated client project." />}

    {selected && <ClientDrawer installation={installation} edit={edit} setEdit={setEdit} tab={tab} setTab={setTab} plans={plans} allFeatures={allFeatures} eligibleReleases={eligibleReleases} operations={operations} busy={busy} onClose={closeClient} onSave={() => save()} onGrant={grant} onRotate={rotateKey} onDeploy={deploy} onDanger={(status) => setDanger({ status, reason: '' })} controlPlane={workspace.controlPlane} />}
    {danger && <DangerPrompt value={danger} onChange={setDanger} busy={busy[`save-${selected}`]} onClose={() => setDanger(null)} onConfirm={() => { const next = danger; setDanger(null); save({ status: next.status, statusReason: next.reason }, `${next.status === 'REVOKED' ? 'Access revoked' : 'Client suspended'} successfully.`); }} />}
  </section>;
}

function ReleaseManager({ workspace, release, setRelease, busy, onPublish }) { const industries = workspace.industryOptions || []; return <details className="admin-card overflow-hidden"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-5"><span className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f3e4e8] text-[#751d39]"><Rocket size={19} /></span><span><strong className="block">Release manager</strong><span className="text-xs text-slate-500">Publish tested version metadata for controlled rollout.</span></span></span><Settings2 size={18} /></summary><div className="grid gap-4 border-t p-5 sm:grid-cols-2 xl:grid-cols-4"><Field label="Semantic version"><input value={release.version} onChange={(e) => setRelease({ ...release, version: e.target.value })} placeholder="1.2.0" /></Field><Field label="Channel"><select value={release.channel} onChange={(e) => setRelease({ ...release, channel: e.target.value })}><option value="stable">Stable</option><option value="beta">Beta</option></select></Field><label className="flex h-11 items-center gap-3 self-end rounded-xl border px-3 text-xs font-black"><input type="checkbox" checked={release.mandatory} onChange={(e) => setRelease({ ...release, mandatory: e.target.checked })} /> Required update</label><button type="button" disabled={busy || !/^\d+\.\d+\.\d+/.test(release.version)} onClick={onPublish} className="admin-btn self-end"><Rocket size={16} />{busy ? 'Publishing...' : 'Publish release'}</button><div className="sm:col-span-2 xl:col-span-4"><p className="mb-2 text-xs font-black">Eligible industries <span className="font-normal text-slate-500">(none selected means all)</span></p><div className="flex flex-wrap gap-2">{industries.map((item) => <ToggleChip key={item.industry} active={release.eligibleIndustries.includes(item.industry)} onClick={() => setRelease((current) => ({ ...current, eligibleIndustries: toggle(current.eligibleIndustries, item.industry) }))}>{item.name}</ToggleChip>)}</div></div><label className="grid gap-2 text-xs font-black sm:col-span-2 xl:col-span-4">Release notes<textarea value={release.notes} maxLength={5000} onChange={(e) => setRelease({ ...release, notes: e.target.value })} className="min-h-24 rounded-xl border p-3 text-sm font-normal" placeholder="Customer-visible improvements, fixes and deployment notes" /></label></div></details>; }

function ClientDrawer(props) {
  const { installation, edit, setEdit, tab, setTab, plans, allFeatures, eligibleReleases, operations, busy, onClose, onSave, onGrant, onRotate, onDeploy, onDanger, controlPlane } = props;
  if (!installation || !edit) return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/30"><div className="rounded-2xl bg-white p-6 shadow-xl">Loading client details...</div></div>;
  const baseFeatures = plans.find((plan) => plan.id === edit.plan)?.features || [];
  const enabled = (feature) => !edit.disabledFeatures.includes(feature) && (baseFeatures.includes(feature) || edit.featureOverrides.includes(feature));
  const setFeature = (feature, checked) => setEdit((current) => ({ ...current, featureOverrides: checked && !baseFeatures.includes(feature) ? [...new Set([...current.featureOverrides, feature])] : current.featureOverrides.filter((item) => item !== feature), disabledFeatures: checked ? current.disabledFeatures.filter((item) => item !== feature) : [...new Set([...current.disabledFeatures, feature])] }));
  const releases = eligibleReleases.filter((item) => item.version !== edit.targetVersion);
  return <div className="fixed inset-0 z-[80] bg-black/35"><aside role="dialog" aria-modal="true" aria-label={`Manage ${installation.companyName}`} className="absolute inset-y-0 right-0 flex w-full max-w-4xl flex-col bg-[#fffdfb] shadow-2xl">
    <header className="border-b bg-white px-4 py-4 sm:px-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#9a5269]">{installation.industry} · {installation.projectSlug}</p><h2 className="mt-1 text-xl font-black sm:text-2xl">{installation.companyName}</h2><p className="mt-1 break-all text-xs text-slate-500">{installation.installationId}</p></div><button type="button" aria-label="Close client details" onClick={onClose} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border"><X size={18} /></button></div><div className="mt-4 flex gap-1 overflow-x-auto">{TABS.map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs font-black ${tab === item ? 'bg-[#751d39] text-white' : 'text-slate-600 hover:bg-[#f8efeb]'}`}>{item}</button>)}</div></header>
    <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-6">
      {tab === 'Overview' && <OverviewTab installation={installation} edit={edit} setEdit={setEdit} />}
      {tab === 'Subscription' && <SubscriptionTab installation={installation} edit={edit} setEdit={setEdit} plans={plans} operations={operations} busy={busy} onGrant={onGrant} />}
      {tab === 'Features & limits' && <FeaturesTab edit={edit} setEdit={setEdit} plans={plans} allFeatures={allFeatures} baseFeatures={baseFeatures} enabled={enabled} setFeature={setFeature} />}
      {tab === 'Deployment' && <DeploymentTab installation={installation} edit={edit} setEdit={setEdit} releases={releases} busy={busy} onDeploy={onDeploy} controlPlane={controlPlane} />}
      {tab === 'Activity' && <ActivityTab rows={operations.activity || []} />}
    </div>
    <footer className="flex flex-wrap items-center justify-between gap-2 border-t bg-white p-4 sm:px-6"><div className="flex flex-wrap gap-2"><button type="button" className="admin-btn-ghost text-amber-800" onClick={() => onDanger('SUSPENDED')}>Suspend</button>{installation.status !== 'REVOKED' && <button type="button" className="admin-btn-ghost text-red-700" onClick={() => onDanger('REVOKED')}><ShieldOff size={15} /> Revoke</button>}<button type="button" className="admin-btn-ghost" disabled={busy[`key-${installation.id}`]} onClick={onRotate}><KeyRound size={15} /> Rotate key</button></div><button type="button" disabled={busy[`save-${installation.id}`]} onClick={onSave} className="admin-btn"><Save size={16} />{busy[`save-${installation.id}`] ? 'Saving...' : 'Save changes'}</button></footer>
  </aside></div>;
}

function OverviewTab({ installation, edit, setEdit }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Status" value={installation.status} /><Metric label="Last seen" value={relativeDate(installation.lastSeenAt)} /><Metric label="Database" value={installation.health?.databaseStatus} /><Metric label="Created" value={formatDate(installation.createdAt, true)} /></div><Panel title="Client profile" note="Contact and account ownership details visible only to the platform owner."><div className="grid gap-4 sm:grid-cols-2"><ContactField name="ownerName" label="Owner name" /><ContactField name="phone" label="Phone" /><ContactField name="email" label="Email" type="email" /><ContactField name="billingEmail" label="Billing email" type="email" /><ContactField name="accountManager" label="Account manager" /><Field label="Tags"><input value={edit.tags} onChange={(e) => setEdit({ ...edit, tags: e.target.value })} placeholder="priority, fashion, north" /></Field></div></Panel><Panel title="Connection" note="Health comes from a signed backend heartbeat; it is not based on the browser."><div className="grid gap-3 sm:grid-cols-3"><Metric label="Service health" value={installation.health?.status} /><Metric label="Products" value={`${installation.usage?.products || 0} / ${installation.limits?.products || 0}`} /><Metric label="Orders this month" value={`${installation.usage?.ordersPerMonth || 0} / ${installation.limits?.ordersPerMonth || 0}`} /></div>{installation.health?.lastError && <p className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-800">{installation.health.lastError}</p>}</Panel><Panel title="Private notes"><Field label="Owner notes"><textarea value={edit.notes} onChange={(e) => setEdit({ ...edit, notes: e.target.value })} className="min-h-24 w-full rounded-xl border p-3 text-sm font-normal" maxLength={1000} /></Field></Panel></div>;
  function ContactField({ name, label, type = 'text' }) { return <Field label={label}><input type={type} value={edit.contact[name]} onChange={(e) => setEdit({ ...edit, contact: { ...edit.contact, [name]: e.target.value } })} /></Field>; }
}
function SubscriptionTab({ installation, edit, setEdit, plans, operations, busy, onGrant }) { return <div className="space-y-5"><Panel title="Access & renewal"><div className="grid gap-4 sm:grid-cols-2"><Field label="Plan"><select value={edit.plan} onChange={(e) => setEdit({ ...edit, plan: e.target.value })}>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></Field><Field label="Status"><select value={edit.status} onChange={(e) => setEdit({ ...edit, status: e.target.value })}>{['TRIAL', 'ACTIVE', 'EXPIRED', 'SUSPENDED', 'REVOKED'].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Billing cycle"><select value={edit.billingCycle} onChange={(e) => setEdit({ ...edit, billingCycle: e.target.value })}>{['TRIAL', 'MONTHLY', 'YEARLY', 'LIFETIME', 'MANUAL'].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Access ends"><input type="date" disabled={edit.billingCycle === 'LIFETIME'} value={edit.endsAt} onChange={(e) => setEdit({ ...edit, endsAt: e.target.value })} /></Field><Field label="Status reason"><input value={edit.statusReason} onChange={(e) => setEdit({ ...edit, statusReason: e.target.value })} /></Field><Field label="Renewal message"><input value={edit.renewalMessage} onChange={(e) => setEdit({ ...edit, renewalMessage: e.target.value })} /></Field></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{['TRIAL', 'MONTHLY', 'YEARLY', 'LIFETIME'].map((value) => <button key={value} type="button" disabled={busy[`save-${installation.id}`]} onClick={() => onGrant(value)} className="h-11 rounded-xl border bg-white text-xs font-black text-[#751d39]">{grantLabel(value)}</button>)}</div></Panel><Panel title="Payment ledger" note={`${operations.paymentTotal || 0} subscription payment record(s).`}><PaymentTable rows={operations.payments || []} /></Panel></div>; }
function FeaturesTab({ edit, setEdit, plans, allFeatures, baseFeatures, enabled, setFeature }) { return <div className="space-y-5"><Panel title="Usage limits" note="Leave an override empty to use the selected plan default."><div className="grid gap-4 sm:grid-cols-2"><Limit label="Active products" value={edit.limitOverrides.products} placeholder={planLimit(plans, edit.plan, 'products')} onChange={(value) => setEdit({ ...edit, limitOverrides: { ...edit.limitOverrides, products: value } })} /><Limit label="Orders per month" value={edit.limitOverrides.ordersPerMonth} placeholder={planLimit(plans, edit.plan, 'ordersPerMonth')} onChange={(value) => setEdit({ ...edit, limitOverrides: { ...edit.limitOverrides, ordersPerMonth: value } })} /></div></Panel><Panel title="Feature access" note="Plan defaults can be overridden for this installation only."><div className="grid gap-2 sm:grid-cols-2">{allFeatures.map((feature) => <label key={feature} className="flex items-center justify-between gap-3 rounded-xl border bg-white p-3 text-sm"><span><strong className="block">{humanize(feature)}</strong><span className="text-[10px] text-slate-500">{baseFeatures.includes(feature) ? 'Included in plan' : 'Individual add-on'}</span></span><input type="checkbox" checked={enabled(feature)} onChange={(e) => setFeature(feature, e.target.checked)} /></label>)}</div></Panel></div>; }
function DeploymentTab({ installation, edit, setEdit, releases, busy, onDeploy, controlPlane }) { return <div className="space-y-5"><Panel title="Release assignment"><div className="grid gap-4 sm:grid-cols-2"><Field label="Update channel"><select value={edit.updateChannel} onChange={(e) => setEdit({ ...edit, updateChannel: e.target.value })}><option value="stable">Stable</option><option value="beta">Beta</option></select></Field><Field label="Target version"><select value={edit.targetVersion} onChange={(e) => setEdit({ ...edit, targetVersion: e.target.value })}><option value={edit.targetVersion}>{edit.targetVersion}</option>{releases.map((item) => <option key={item.version} value={item.version}>{item.version}{item.mandatory ? ' · required' : ''}</option>)}</select></Field></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Installed" value={installation.lastValidatedVersion || installation.appVersion} /><Metric label="Target" value={installation.targetVersion} /><Metric label="State" value={installation.deployment?.phase || 'Not started'} /></div></Panel><Panel title="Managed deployment" note="The hook starts a provider build. Live is shown only after that target version reports back.">{!controlPlane?.deploymentHooksReady && <p className="mb-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-900">Configure platform credential encryption before saving private hooks.</p>}<div className="grid gap-4"><Field label="Store deployment URL"><input value={edit.deploymentUrl} onChange={(e) => setEdit({ ...edit, deploymentUrl: e.target.value })} placeholder="https://client.example.com" /></Field><Field label={installation.deployment?.hasHook ? 'Replace private deploy hook' : 'Private deploy hook'}><input type="password" autoComplete="new-password" value={edit.deployHookUrl || ''} onChange={(e) => setEdit({ ...edit, deployHookUrl: e.target.value })} placeholder={installation.deployment?.hasHook ? 'Leave blank to keep current hook' : 'Provider deploy hook URL'} /></Field><div className="flex flex-wrap gap-2"><button type="button" className="admin-btn" disabled={busy[`deploy-${installation.id}`] || !installation.deployment?.hasHook} onClick={onDeploy}><Rocket size={16} />{busy[`deploy-${installation.id}`] ? 'Starting...' : `Deploy ${installation.targetVersion}`}</button>{installation.deploymentUrl && <a href={installation.deploymentUrl} target="_blank" rel="noreferrer" className="admin-btn-ghost"><ExternalLink size={16} /> Open client</a>}{installation.deployment?.hasHook && <button type="button" className="admin-btn-ghost" onClick={() => setEdit({ ...edit, deployHookUrl: '__REMOVE__' })}>Remove hook</button>}</div>{installation.deployment?.last && <p className="text-xs text-slate-600">{installation.deployment.phase} · {installation.deployment.last.message} · {formatDate(installation.deployment.last.completedAt || installation.deployment.last.requestedAt)}</p>}</div></Panel></div>; }
function ActivityTab({ rows }) { return <Panel title="Client activity" note="Owner-only control changes and subscription events."><div className="space-y-2">{rows.length ? rows.map((item) => <div key={item.id} className="flex gap-3 rounded-xl border bg-white p-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#f5e9ec] text-[#751d39]"><Activity size={16} /></span><div><strong className="block text-sm">{humanize(item.action)}</strong><p className="text-xs text-slate-500">{item.actor} · {formatDate(item.createdAt)}</p></div></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No client activity recorded yet.</p>}</div></Panel>; }

function DangerPrompt({ value, onChange, onClose, onConfirm, busy }) { return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/45 p-4"><div role="alertdialog" className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-red-50 text-red-700"><ShieldOff /></span><h2 className="mt-4 text-xl font-black">{value.status === 'REVOKED' ? 'Revoke client access?' : 'Suspend this client?'}</h2><p className="mt-2 text-sm leading-6 text-slate-600">Commerce changes will be blocked after the signed cache expires. Record a reason for the account history.</p><Field label="Reason"><textarea autoFocus value={value.reason} onChange={(e) => onChange({ ...value, reason: e.target.value })} className="mt-3 min-h-24 w-full rounded-xl border p-3 text-sm" maxLength={500} /></Field><div className="mt-5 flex justify-end gap-2"><button type="button" className="admin-btn-ghost" onClick={onClose}>Cancel</button><button type="button" disabled={busy || value.reason.trim().length < 3} className="admin-btn bg-red-700" onClick={onConfirm}>Confirm {value.status.toLowerCase()}</button></div></div></div>; }
function ClientRow({ item, onOpen, busy }) { return <tr className="border-t hover:bg-[#fffdfb]"><td className="p-4"><strong>{item.companyName}</strong><p className="mt-1 text-xs text-slate-500">{item.industry} · {item.contact?.ownerName || item.projectSlug}</p></td><td><Status value={item.status} /><p className="mt-1 text-xs text-slate-500">{item.plan} · {accessLabel(item)}</p></td><td><p className="text-xs font-bold">{item.usage?.products || 0}/{item.limits?.products || 0} products</p><p className="mt-1 text-xs text-slate-500">{item.usage?.ordersPerMonth || 0}/{item.limits?.ordersPerMonth || 0} orders</p></td><td><Health value={item.health?.status} /><p className="mt-1 text-xs text-slate-500">{relativeDate(item.lastSeenAt)}</p></td><td><p className="text-xs font-bold">{item.lastValidatedVersion || item.appVersion}</p><p className="mt-1 text-xs text-slate-500">Target {item.targetVersion}</p></td><td className="pr-4 text-right"><button type="button" disabled={busy} onClick={onOpen} className="rounded-xl border px-3 py-2 text-xs font-black text-[#751d39]">{busy ? 'Opening...' : 'Manage'}</button></td></tr>; }
function ClientCard({ item, onOpen }) { return <article className="admin-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider text-[#9a5269]">{item.industry}</p><h2 className="mt-1 font-black">{item.companyName}</h2><p className="text-xs text-slate-500">{item.plan} · {accessLabel(item)}</p></div><Status value={item.status} /></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Health" value={item.health?.status} /><Metric label="Products" value={`${item.usage?.products || 0}/${item.limits?.products || 0}`} /><Metric label="Version" value={item.lastValidatedVersion || item.appVersion} /></div><button type="button" onClick={onOpen} className="admin-btn mt-4 w-full">Manage client</button></article>; }
function Summary({ icon: Icon, label, value, tone = '', onClick }) { const colors = tone === 'green' ? 'bg-emerald-50 text-emerald-700' : tone === 'amber' ? 'bg-amber-50 text-amber-700' : tone === 'red' ? 'bg-red-50 text-red-700' : 'bg-[#f6e9ed] text-[#7a1c39]'; const Tag = onClick ? 'button' : 'div'; return <Tag type={onClick ? 'button' : undefined} onClick={onClick} className="admin-card flex min-w-0 items-center gap-3 p-4 text-left"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${colors}`}><Icon size={18} /></span><span className="min-w-0"><strong className="block truncate text-lg">{value}</strong><span className="block truncate text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span></span></Tag>; }
function Panel({ title, note, children }) { return <section className="rounded-2xl border bg-white p-4 sm:p-5"><h3 className="font-black">{title}</h3>{note && <p className="mt-1 text-xs leading-5 text-slate-500">{note}</p>}<div className="mt-4">{children}</div></section>; }
function Notice({ icon: Icon, title, children }) { return <div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><Icon className="shrink-0" size={19} /><div><strong>{title}</strong><p className="mt-1 text-xs leading-5">{children}</p></div></div>; }
function Field({ label, children }) { return <label className="grid min-w-0 gap-2 text-xs font-black"><span>{label}</span><span className="[&>input]:h-11 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:px-3 [&>input]:text-sm [&>input]:font-normal [&>select]:h-11 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:bg-white [&>select]:px-3 [&>select]:text-sm [&>select]:font-normal">{children}</span></label>; }
function FilterSelect({ label, value, onChange, children }) { return <label className="relative"><Filter className="pointer-events-none absolute left-3 top-3 text-slate-400" size={15} /><select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className="h-11 w-full rounded-xl border bg-white pl-9 pr-7 text-xs font-bold"><option value="">All {label.toLowerCase()}</option>{children}</select></label>; }
function Metric({ label, value }) { return <div className="min-w-0 rounded-xl bg-[#fbf7f4] p-3"><p className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</p><strong className="mt-1 block truncate text-xs">{value || 'Not available'}</strong></div>; }
function Status({ value }) { const good = ['ACTIVE', 'TRIAL', 'PAID'].includes(value); return <span className={`inline-flex rounded-full px-2.5 py-1 text-[9px] font-black ${good ? 'bg-emerald-100 text-emerald-800' : value === 'REVOKED' || value === 'FAILED' ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800'}`}>{value}</span>; }
function Health({ value }) { const color = value === 'ONLINE' ? 'text-emerald-700' : value === 'ERROR' ? 'text-red-700' : 'text-amber-700'; return <span className={`text-xs font-black ${color}`}>{value || 'OFFLINE'}</span>; }
function ToggleChip({ active, onClick, children }) { return <button type="button" onClick={onClick} className={`rounded-full border px-3 py-2 text-xs font-black ${active ? 'border-[#751d39] bg-[#751d39] text-white' : 'bg-white text-slate-600'}`}>{active && <Check className="mr-1 inline" size={13} />}{children}</button>; }
function Limit({ label, value, placeholder, onChange }) { return <label className="grid gap-1.5 text-xs font-bold text-slate-700">{label}<input type="number" min="0" step="1" value={value} placeholder={`Plan default: ${Number(placeholder || 0).toLocaleString('en-IN')}`} onChange={(e) => onChange(e.target.value)} className="h-11 rounded-xl border px-3 text-sm font-normal" /></label>; }
function PaymentTable({ rows }) { if (!rows.length) return <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No subscription payments yet.</p>; return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="text-[9px] uppercase tracking-wider text-slate-500"><tr><th className="pb-3">Date</th><th>Plan</th><th>Cycle</th><th>Amount</th><th>Status</th><th>Reference</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t"><td className="py-3">{formatDate(row.paidAt || row.createdAt, true)}</td><td>{row.plan}</td><td>{row.billingCycle}</td><td>₹{Number(row.amount || 0).toLocaleString('en-IN')}</td><td><Status value={row.status} /></td><td className="max-w-[150px] truncate">{row.razorpayPaymentId || row.receipt}</td></tr>)}</tbody></table></div>; }
function Pagination({ value, onChange }) { return <div className="flex items-center justify-between"><p className="text-xs text-slate-500">Page {value.page} of {value.pages} · {value.total} clients</p><div className="flex gap-2"><button type="button" aria-label="Previous page" disabled={value.page <= 1} onClick={() => onChange(value.page - 1)} className="grid h-10 w-10 place-items-center rounded-xl border bg-white disabled:opacity-40"><ChevronLeft size={17} /></button><button type="button" aria-label="Next page" disabled={value.page >= value.pages} onClick={() => onChange(value.page + 1)} className="grid h-10 w-10 place-items-center rounded-xl border bg-white disabled:opacity-40"><ChevronRight size={17} /></button></div></div>; }
function toEdit(item) { return { plan: item.plan, status: item.status, billingCycle: item.billingCycle, endsAt: item.endsAt ? new Date(item.endsAt).toISOString().slice(0, 10) : '', targetVersion: item.targetVersion, updateChannel: item.updateChannel, deploymentUrl: item.deploymentUrl || '', notes: item.notes || '', renewalMessage: item.renewalMessage || '', statusReason: item.statusReason || '', contact: { ownerName: item.contact?.ownerName || '', phone: item.contact?.phone || '', email: item.contact?.email || '', billingEmail: item.contact?.billingEmail || '', accountManager: item.contact?.accountManager || '' }, tags: (item.tags || []).join(', '), featureOverrides: [...(item.featureOverrides || [])], disabledFeatures: [...(item.disabledFeatures || [])], limitOverrides: { products: item.limitOverrides?.products ?? '', ordersPerMonth: item.limitOverrides?.ordersPerMonth ?? '' } }; }
function planLimit(plans, plan, key) { return plans.find((item) => item.id === plan)?.limits?.[key] || 0; }
function toggle(values, value) { return values.includes(value) ? values.filter((item) => item !== value) : [...values, value]; }
function grantLabel(value) { return ({ TRIAL: '30-day trial', MONTHLY: '1 month', YEARLY: '1 year', LIFETIME: 'Lifetime' })[value] || value; }
function accessLabel(item) { return item.billingCycle === 'LIFETIME' ? 'Lifetime' : item.daysRemaining == null ? item.billingCycle : `${item.daysRemaining} days`; }
function relativeDate(value) { if (!value) return 'Never'; const date = new Date(value); const hours = Math.floor((Date.now() - date.getTime()) / 3600000); return hours < 1 ? 'Just now' : hours < 24 ? `${hours}h ago` : `${Math.floor(hours / 24)}d ago`; }
function formatDate(value, dateOnly = false) { if (!value) return 'Not available'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Not available' : date.toLocaleString('en-IN', dateOnly ? { dateStyle: 'medium' } : { dateStyle: 'medium', timeStyle: 'short' }); }
function humanize(value) { return String(value || '').replace(/_/g, ' ').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^./, (letter) => letter.toUpperCase()); }
