import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckCheck, ExternalLink, Image, Loader2, MessageCircle, Plus, RefreshCw, Search, Send, ShieldCheck, Sparkles, Trash2, Video, X } from 'lucide-react';
import api from '../../services/api';
import './SocialWorkspace.css';

const time = value => value ? new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : '';
const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const pendingStatus = status => ['queued', 'processing', 'uploading', 'publishing', 'verifying'].includes(status);
const safeLink = value => /^https:\/\//i.test(String(value || '')) ? value : '';
const requestId = () => window.crypto?.randomUUID?.() || `reply-${Date.now()}-${Math.random().toString(36).slice(2)}`;
function Instagram({ size = 24, ...props }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true" {...props}><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.6" cy="6.4" r=".9" fill="currentColor" stroke="none" /></svg>; }
function Facebook({ size = 24, ...props }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}><path d="M14 22v-9h3l.5-3H14V8c0-1 .3-1.5 1.5-1.5H18V3.2c-.5-.1-1.8-.2-3-.2-3 0-5 1.8-5 5v2H7v3h3v9z" /></svg>; }
function Brand({ provider, ...props }) { const Icon = provider === 'instagram' ? Instagram : Facebook; return <Icon {...props} />; }
function Empty({ Icon = MessageCircle, title, children }) { return <div className="social-empty"><span><Icon size={30} /></span><h3>{title}</h3><p>{children}</p></div>; }
function Spin() { return <Loader2 size={16} className="social-spin" />; }

export default function SocialWorkspace() {
  const [tab, setTab] = useState(new URLSearchParams(window.location.search).has('connectionSession') ? 'accounts' : 'inbox');
  const [storeId, setStoreId] = useState(new URLSearchParams(window.location.search).get('storeId') || '');
  const [status, setStatus] = useState(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [unread, setUnread] = useState(0);
  const endpoint = useCallback(path => `/social${path}${path.includes('?') ? '&' : '?'}${storeId ? `storeId=${encodeURIComponent(storeId)}` : ''}`, [storeId]);
  const client = useMemo(() => ({
    get: path => api.get(endpoint(path), { silent: true }), post: (path, body) => api.post(endpoint(path), body),
    put: (path, body) => api.put(endpoint(path), body), patch: (path, body) => api.patch(endpoint(path), body), delete: path => api.delete(endpoint(path)),
  }), [endpoint]);
  const refresh = useCallback(async () => { const next = await client.get('/status'); setStatus(next); return next; }, [client]);
  useEffect(() => { let live = true; setStatus(null); client.get('/status').then(next => { if (live) { setStatus(next); if (!next.permissions.inbox) setTab(next.permissions.publish ? 'publish' : 'accounts'); } }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, [client]);
  useEffect(() => {
    const code = new URLSearchParams(window.location.search).get('socialError');
    if (code) setError(code === 'cancelled' ? 'Connection was cancelled. You can connect again when ready.' : 'Meta could not complete the connection. Check the app configuration and permissions, then try again.');
  }, []);
  const report = message => { setNotice(message); setError(''); };
  return <div className="social-studio">
    <header className="social-heading"><div><p className="social-eyebrow">YOUR STORE, CONNECTED</p><h1>Social studio<span>✦</span></h1><p>Conversations to connections. Products to posts.</p></div><div className="social-heading-actions">{status?.stores?.length > 1 && <label className="social-sr">Store<select value={storeId || status.store.id} onChange={e => { setStoreId(e.target.value); setError(''); setNotice(''); }} aria-label="Choose store">{status.stores.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button className="social-primary" onClick={() => setTab('accounts')}><Plus size={17} /> Connect account</button></div></header>
    <div className="social-overview"><div><span className="social-mini-icon"><Instagram /></span><p><strong>{status?.accounts.filter(a => a.status === 'connected').length || 0}</strong><span>Connected accounts</span></p></div><div><span className="social-mini-icon"><MessageCircle /></span><p><strong>{unread}</strong><span>Unread conversations</span></p></div><div className="social-overview-note"><ShieldCheck /><p>Your accounts. Your control.<span>Review every reply and post before sending.</span></p></div></div>
    <nav className="social-tabs" aria-label="Social studio sections">{[['inbox', MessageCircle, 'Shared inbox'], ['publish', Sparkles, 'Create & publish'], ['accounts', Instagram, 'Accounts']].filter(([id]) => !status || id === 'accounts' || (id === 'inbox' ? status.permissions.inbox : status.permissions.publish)).map(([id, Icon, label]) => <button key={id} onClick={() => { setTab(id); setNotice(''); }} className={tab === id ? 'is-active' : ''} aria-current={tab === id ? 'page' : undefined}><Icon size={18} /><span>{label}</span>{id === 'inbox' && unread > 0 && <b>{unread}</b>}</button>)}</nav>
    {error && <div className="social-alert" role="alert">{error}<button aria-label="Dismiss error" onClick={() => setError('')}><X size={16} /></button></div>}
    {notice && <div className="social-notice" role="status"><Check size={17} />{notice}<button aria-label="Dismiss notification" onClick={() => setNotice('')}><X size={16} /></button></div>}
    {!status ? <div className="social-loading">{!error && <Spin />}{error ? <button onClick={() => refresh().catch(e => setError(e.message))}>Try again</button> : 'Loading your workspace…'}</div> : <div key={status.store.id}>
      {!status.configured && tab !== 'accounts' && <div className="social-setup-hint"><ShieldCheck size={21} /><div><strong>Connect your Meta app to go live</strong><p>You can prepare product drafts and video previews while account setup is completed.</p></div><button onClick={() => setTab('accounts')}>View setup <ArrowRight size={15} /></button></div>}
      {tab === 'inbox' && <Inbox client={client} status={status} refresh={refresh} setUnread={setUnread} onError={setError} onNotice={report} />}
      {tab === 'publish' && <Publisher client={client} status={status} onError={setError} onNotice={report} />}
      {tab === 'accounts' && <Accounts client={client} status={status} refresh={refresh} onError={setError} onNotice={report} />}
    </div>}
  </div>;
}

function Accounts({ client, status, refresh, onError, onNotice }) {
  const sessionId = new URLSearchParams(window.location.search).get('connectionSession');
  const [pending, setPending] = useState(null), [selected, setSelected] = useState([]), [busy, setBusy] = useState(''), [confirm, setConfirm] = useState(null);
  useEffect(() => { let live = true; if (sessionId) client.get('/pending/' + sessionId).then(data => { if (live) setPending(data); }).catch(e => { if (live) onError(e.message); }); return () => { live = false; }; }, [client, sessionId, onError]);
  const action = async (id, fn) => { setBusy(id); try { await fn(); } catch (e) { onError(e.message); } finally { setBusy(''); } };
  return <div className="social-accounts">
    <section className="social-connect-card"><div><p className="social-eyebrow">ONE WORKSPACE. BOTH CHANNELS.</p><h2>Bring your business together.</h2><p>Connect your Facebook Pages and their linked Instagram professional accounts. Read customer messages, send replies and publish products from here.</p><div className="social-channel-pills"><span><Instagram size={17} /> Instagram Business / Creator</span><span><Facebook size={17} /> Facebook Pages</span></div><button className="social-primary" disabled={Boolean(busy) || !status.configured || !status.permissions.connect} onClick={() => action('connect', async () => { const result = await client.post('/connect', {}); window.location.assign(result.url); })}>{busy === 'connect' ? <Spin /> : <Facebook size={17} />} Continue with Facebook</button><small>Instagram connects through its linked Page. Personal profiles and personal inboxes are not supported by Meta.</small></div><div className="social-connect-art" aria-hidden="true"><Instagram size={44} /><span>+</span><Facebook size={44} /><div><MessageCircle size={30} /> Samira Social studio</div></div></section>
    {!status.configured && <section className="social-panel social-setup"><h3>One-time app setup</h3><p>A store owner needs to configure the Meta app, callback and signed webhooks. Meta approval is required before connecting accounts outside the app’s test team.</p><p className="social-config-missing">Missing: {status.missing.join(', ')}</p><p>The setup guide is included at <code>docs/social-workspace.md</code>. Existing server settings are preserved.</p><a href="https://developers.facebook.com/apps/" target="_blank" rel="noreferrer">Open Meta for Developers <ExternalLink size={14} /></a></section>}
    {pending && <section className="social-panel"><h3>Choose Pages to connect</h3><p>Only the Pages you select and their linked Instagram accounts are added to this store.</p>{pending.pages.length ? pending.pages.map(p => <label key={p.id} className="social-page-choice"><input type="checkbox" checked={selected.includes(p.id)} onChange={() => setSelected(previous => previous.includes(p.id) ? previous.filter(id => id !== p.id) : [...previous, p.id])} /><Facebook size={22} /><span><strong>{p.name}</strong><small>{p.instagram ? `Instagram: @${p.instagram.username || p.instagram.id}` : 'No professional Instagram account linked'}</small></span></label>) : <p>No eligible Pages were returned. Check your Page access in Meta Business Suite and connect again.</p>}{pending.missingPermissions.length > 0 && <p className="social-inline-warning">Some permissions were declined. Features are enabled only when their permissions are granted.</p>}<button className="social-primary" disabled={!selected.length || Boolean(busy)} onClick={() => action('activate', async () => { await client.post('/pending/' + sessionId, { pageIds: selected }); setPending(null); const url = new URL(window.location.href); url.searchParams.delete('connectionSession'); window.history.replaceState({}, '', url); await refresh(); onNotice('Selected accounts connected. Sync the inbox to import conversations.'); })}>{busy === 'activate' && <Spin />} Connect selected accounts</button></section>}
    <div className="social-section-title"><h2>Connected accounts</h2><span>{status.store.name}</span></div>
    {!status.accounts.length ? <Empty Icon={Instagram} title="Your accounts will appear here">Connect a Page to bring your business conversations and product posts into one place.</Empty> : <div className="social-account-grid">{status.accounts.map(a => <section key={a._id} className="social-panel social-account-card"><div className="social-account-title"><span className={`social-brand ${a.provider}`}><Brand provider={a.provider} size={24} /></span><div><h3>{a.name}</h3><small>{a.username ? '@' + a.username : 'Facebook Page'}</small></div><span className={`social-status ${a.status}`}>{a.status}</span></div><div className="social-access"><span>{a.capabilities.inbox ? <Check size={14} /> : <X size={14} />} Messaging</span><span>{a.capabilities.publish ? <Check size={14} /> : <X size={14} />} Publishing</span><span>{a.subscribed ? <Check size={14} /> : <X size={14} />} Live updates</span></div>{a.lastError && <p className="social-inline-warning">{a.lastError}</p>}<small>Last sync: {time(a.lastSyncedAt) || 'Not synced yet'}{a.expiresAt && <> · Reconnect before {new Date(a.expiresAt).toLocaleDateString('en-IN')}</>}</small><div className="social-account-actions"><button disabled={Boolean(busy) || !a.capabilities.inbox || !status.permissions.inbox} onClick={() => action(a._id, async () => { await client.post(`/accounts/${a._id}/sync`, {}); await refresh(); onNotice('Inbox synced.'); })}>{busy === a._id ? <Spin /> : <RefreshCw size={15} />} Sync inbox</button>{a.syncCursor && <button disabled={Boolean(busy) || !status.permissions.inbox} onClick={() => action(a._id, async () => { await client.post(`/accounts/${a._id}/sync`, { older: true }); await refresh(); onNotice('Older conversations imported.'); })}>Import older</button>}{status.permissions.connect && <button className="social-danger" onClick={() => setConfirm(a)}>Disconnect</button>}</div></section>)}</div>}
    <p className="social-footnote">Meta may limit message history. Instagram requests older than 30 days may be unavailable. Customer messages open a 24-hour reply window.</p>
    {confirm && <Confirm title={`Disconnect ${confirm.name}?`} action="Disconnect account" busy={Boolean(busy)} onClose={() => setConfirm(null)} onConfirm={() => action('disconnect', async () => { await client.delete('/accounts/' + confirm._id); setConfirm(null); await refresh(); onNotice('Account disconnected. Its locally stored conversations and access token were removed.'); })}>This removes its access token and message history from this workspace. Published posts remain on Meta. You can reconnect later.</Confirm>}
  </div>;
}

function Inbox({ client, status, refresh, setUnread, onError, onNotice }) {
  const [provider, setProvider] = useState(''), [filter, setFilter] = useState('open'), [search, setSearch] = useState(''), [page, setPage] = useState(0);
  const [threads, setThreads] = useState([]), [hasMore, setHasMore] = useState(false), [selected, setSelected] = useState(''), [detail, setDetail] = useState(null), [loading, setLoading] = useState(true), [syncing, setSyncing] = useState(false);
  const [text, setText] = useState(''), [sending, setSending] = useState(false), [productPicker, setProductPicker] = useState(false), [sendState, setSendState] = useState('');
  const replyAttempt = useRef(null), scroll = useRef(null), conversationVersion = useRef(0);
  const query = `/threads?provider=${provider}&state=${filter}&search=${encodeURIComponent(search)}&page=${page}`;
  const loadThreads = useCallback(async () => { const data = await client.get(query); setThreads(data.threads); setHasMore(data.hasMore); setUnread(data.unread); }, [client, query, setUnread]);
  useEffect(() => { let live = true; setLoading(true); const load = () => client.get(query).then(data => { if (live) { setThreads(data.threads); setHasMore(data.hasMore); setUnread(data.unread); setLoading(false); } }).catch(e => { if (live) { onError(e.message); setLoading(false); } }); const timeout = setTimeout(load, 250); const interval = setInterval(() => { if (!document.hidden) load(); }, 15000); return () => { live = false; clearTimeout(timeout); clearInterval(interval); }; }, [client, query, setUnread, onError]);
  useEffect(() => {
    let live = true; conversationVersion.current += 1; setDetail(null); setText(''); setSendState(''); setSending(false); replyAttempt.current = null;
    if (!selected) return undefined;
    const load = async () => { try { const data = await client.get('/threads/' + selected); if (live) { setDetail(previous => ({ ...data, messages: previous?.messages?.length > 50 ? [...previous.messages.filter(m => !data.messages.some(n => n._id === m._id)), ...data.messages].sort((a, b) => new Date(a.sentAt) - new Date(b.sentAt) || a._id.localeCompare(b._id)) : data.messages })); if (data.thread.lastInboundAt) await client.patch('/threads/' + selected, { readAt: data.thread.lastInboundAt }); } } catch (e) { if (live) onError(e.message); } };
    load(); const interval = setInterval(() => { if (!document.hidden) load(); }, 10000);
    return () => { live = false; conversationVersion.current += 1; clearInterval(interval); };
  }, [client, selected, onError]);
  const lastMessage = detail?.messages?.[detail.messages.length - 1]?._id;
  useEffect(() => { scroll.current?.scrollTo?.({ top: scroll.current.scrollHeight, behavior: 'smooth' }); }, [lastMessage]);
  const act = async fn => { try { await fn(); } catch (e) { onError(e.message); } };
  const sync = async () => { setSyncing(true); try { for (const account of status.accounts.filter(a => a.capabilities.inbox && a.status === 'connected')) await client.post(`/accounts/${account._id}/sync`, {}); await Promise.all([refresh(), loadThreads()]); onNotice('Recent conversations synced.'); } catch (e) { onError(e.message); } finally { setSyncing(false); } };
  const send = async event => {
    event.preventDefault(); if (!text.trim() || sending || !detail?.thread.canReply) return;
    const version = conversationVersion.current;
    setSending(true);
    if (!replyAttempt.current || replyAttempt.current.text !== text.trim() || sendState === 'failed') replyAttempt.current = { text: text.trim(), clientId: requestId() };
    try {
      const result = await client.post(`/threads/${selected}/reply`, replyAttempt.current);
      if (version !== conversationVersion.current) return;
      setSendState(result.message.status);
      if (result.message.status === 'sent') { setText(''); replyAttempt.current = null; }
      else onError(result.message.error || 'The reply is awaiting confirmation. Sync before trying again.');
      const data = await client.get('/threads/' + selected);
      if (version !== conversationVersion.current) return;
      setDetail(data); await loadThreads();
    } catch (e) { if (version === conversationVersion.current) onError(e.message); }
    finally { if (version === conversationVersion.current) setSending(false); }
  };
  const resolveThread = async () => {
    const version = conversationVersion.current, resolved = !detail.thread.resolved;
    await client.patch('/threads/' + selected, { resolved });
    if (version !== conversationVersion.current) return;
    setDetail(current => ({ ...current, thread: { ...current.thread, resolved } }));
    await loadThreads();
  };
  const loadOlder = async () => {
    const version = conversationVersion.current;
    if (detail.hasMore && detail.messages.length) {
      const older = await client.get(`/threads/${selected}?before=${detail.messages[0]._id}`);
      if (version !== conversationVersion.current) return;
      setDetail(current => ({ ...current, messages: [...older.messages.filter(message => !current.messages.some(item => item._id === message._id)), ...current.messages], hasMore: older.hasMore }));
    } else {
      await client.post(`/threads/${selected}/history`, {});
      if (version !== conversationVersion.current) return;
      const data = await client.get('/threads/' + selected);
      if (version === conversationVersion.current) setDetail(data);
    }
  };
  const account = status.accounts.find(a => a._id === detail?.thread.connectionId);
  return <section className={`social-inbox ${selected ? 'has-thread' : ''}`}>
    <aside className="social-thread-list"><div className="social-inbox-title"><h2>Messages</h2><button aria-label="Sync all inboxes" disabled={syncing || !status.accounts.some(a => a.capabilities.inbox)} onClick={sync}>{syncing ? <Spin /> : <RefreshCw size={16} />}</button></div><label className="social-search"><Search size={17} /><input aria-label="Search conversations" placeholder="Search name or message" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /></label><div className="social-inbox-filters"><select aria-label="Message channel" value={provider} onChange={e => { setProvider(e.target.value); setPage(0); }}><option value="">All channels</option><option value="instagram">Instagram</option><option value="facebook">Facebook</option></select><select aria-label="Conversation status" value={filter} onChange={e => { setFilter(e.target.value); setPage(0); }}><option value="open">Open</option><option value="unread">Unread</option><option value="resolved">Resolved</option><option value="">All messages</option></select></div>
      <div className="social-threads">{loading ? <div className="social-loading"><Spin /> Loading conversations…</div> : !threads.length ? <Empty title="A fresh start">{status.accounts.length ? 'Sync your accounts to bring in customer conversations, or try another filter.' : 'Connect an account in Accounts to start receiving messages.'}</Empty> : threads.map(t => <button key={t._id} className={`social-thread ${t._id === selected ? 'is-selected' : ''} ${t.unread ? 'is-unread' : ''}`} onClick={() => setSelected(t._id)}><span className={`social-avatar ${t.provider}`}>{(t.participantName || 'C').slice(0, 1).toUpperCase()}<Brand provider={t.provider} size={14} /></span><span className="social-thread-copy"><span><strong>{t.participantName || 'Customer ' + t.participantId.slice(-4)}</strong>{t.unread && <i />}</span><small>{t.preview || 'Attachment'}</small><time>{time(t.lastMessageAt)}</time></span></button>)}</div><div className="social-pager"><button disabled={page === 0} onClick={() => setPage(p => p - 1)}>Previous</button><span>{page + 1}</span><button disabled={!hasMore} onClick={() => setPage(p => p + 1)}>Next</button></div></aside>
    <div className="social-conversation">{!selected ? <Empty Icon={MessageCircle} title="Every conversation, in one place">Choose a customer to view their messages and reply. Your Facebook and Instagram conversations stay organised here.</Empty> : !detail ? <div className="social-loading"><Spin /> Opening conversation…</div> : <><header className="social-conversation-head"><button className="social-thread-back" aria-label="Back to conversations" onClick={() => setSelected('')}><ArrowLeft size={19} /></button><span className={`social-brand ${detail.thread.provider}`}><Brand provider={detail.thread.provider} size={21} /></span><div><h3>{detail.thread.participantName || 'Customer ' + detail.thread.participantId.slice(-4)}</h3><small>{account?.name || detail.thread.provider} · {detail.thread.resolved ? 'Resolved' : 'Open'}</small></div><button className="social-resolve" onClick={() => act(resolveThread)}><CheckCheck size={17} /><span>{detail.thread.resolved ? 'Reopen' : 'Resolve'}</span></button></header>
      <div className="social-messages" ref={scroll}>{(detail.hasMore || detail.thread.historyCursor) && <button className="social-load-older" onClick={() => act(loadOlder)}>Load older messages</button>}{detail.messages.map(m => <article key={m._id} className={`social-message ${m.direction}`}><div>{m.text && <p>{m.text}</p>}{m.attachments?.map((a, i) => safeLink(a.url) && <a key={i} href={a.url} target="_blank" rel="noreferrer">{a.type === 'image' ? <img src={a.url} alt="Customer attachment" loading="lazy" referrerPolicy="no-referrer" /> : <><ExternalLink size={15} /> Open {a.type || 'attachment'}</>}</a>)}{m.error && <small className="social-message-error">{m.error}</small>}</div><footer>{time(m.sentAt || m.createdAt)}{m.direction === 'outbound' && <span>{m.status === 'sent' ? <CheckCheck size={13} /> : m.status}</span>}</footer></article>)}</div>
      <form className="social-reply" onSubmit={send}><div className="social-reply-window"><span className={detail.thread.canReply ? 'is-open' : ''} />{detail.thread.canReply ? 'Reply window open' : 'Reply window closed — a new customer message is needed'}<a href="https://business.facebook.com/latest/inbox" target="_blank" rel="noreferrer">Meta inbox <ExternalLink size={12} /></a></div><textarea aria-label="Write your reply" placeholder={detail.thread.canReply ? 'Write a thoughtful reply…' : 'Meta allows replies within 24 hours of a customer’s message.'} maxLength={1000} value={text} onChange={e => { setText(e.target.value); setSendState(''); }} disabled={!detail.thread.canReply || !status.permissions.reply || sending} /><div className="social-reply-actions"><button type="button" disabled={!detail.thread.canReply || !status.permissions.reply} onClick={() => setProductPicker(true)}><Plus size={15} /> Add product link</button><span>{text.length}/1000</span><button type="submit" className="social-primary" disabled={!text.trim() || !detail.thread.canReply || !status.permissions.reply || sending || ['unknown', 'sending'].includes(sendState)}>{sending ? <Spin /> : <Send size={15} />} Send reply</button></div><small>Replies are sent only when you choose Send. Links in Instagram messages open separately.</small></form></> }</div>
    {productPicker && <Modal title="Share a product" onClose={() => setProductPicker(false)}><ProductPicker client={client} onSelect={p => { const next = `${text}${text ? '\n\n' : ''}${p.name} · ${money(p.price)}\n${p.url}`; if (next.length > 1000) { onError('Shorten the reply before adding this product link.'); return; } setText(next); setSendState(''); setProductPicker(false); }} /></Modal>}
  </section>;
}

function Publisher({ client, status, onError, onNotice }) {
  const [post, setPost] = useState(null), [product, setProduct] = useState(null), [images, setImages] = useState([]), [caption, setCaption] = useState(''), [kind, setKind] = useState('photos');
  const [history, setHistory] = useState([]), [historyMore, setHistoryMore] = useState(false), [historyPage, setHistoryPage] = useState(0), [picker, setPicker] = useState(false), [busy, setBusy] = useState(''), [selected, setSelected] = useState([]), [confirm, setConfirm] = useState(false), [deletePost, setDeletePost] = useState(null);
  const loadHistory = useCallback(async () => { const result = await client.get('/posts?page=' + historyPage); setHistory(result.posts); setHistoryMore(result.hasMore); }, [client, historyPage]);
  useEffect(() => { let live = true; client.get('/posts?page=' + historyPage).then(data => { if (live) { setHistory(data.posts); setHistoryMore(data.hasMore); } }).catch(e => { if (live) onError(e.message); }); return () => { live = false; }; }, [client, historyPage, onError]);
  const jobId = post?._id, jobRunning = pendingStatus(post?.status) || pendingStatus(post?.videoStatus);
  useEffect(() => { if (!jobId || !jobRunning) return undefined; let live = true; const interval = setInterval(async () => { try { const result = await client.get('/posts/' + jobId); if (live) { setPost(result.post); if (!pendingStatus(result.post.status) && !pendingStatus(result.post.videoStatus)) await loadHistory(); } } catch (e) { if (live) onError(e.message); } }, 5000); return () => { live = false; clearInterval(interval); }; }, [client, jobId, jobRunning, loadHistory, onError]);
  const act = async (id, fn) => { setBusy(id); try { await fn(); } catch (e) { onError(e.message); } finally { setBusy(''); } };
  const choose = p => { setProduct(p); setImages(p.images.slice(0, 4)); setCaption(`${p.name}\n${money(p.price)}\n\n${p.url}`); setKind('photos'); setPost(null); setPicker(false); setSelected([]); };
  const save = async () => { if (!product) throw new Error('Choose a product first.'); const body = { productId: product._id, images, caption, kind }; const result = await (post ? client.put('/posts/' + post._id, body) : client.post('/posts', body)); setPost(result.post); await loadHistory(); return result.post; };
  const load = async saved => { setPost(saved); setProduct({ _id: saved.productId, name: saved.productName, price: saved.productPrice, url: saved.productUrl, images: saved.images }); setImages(saved.images); setCaption(saved.caption); setKind(saved.kind); setSelected([]); if (saved.status === 'draft') { const result = await client.get('/products?search=' + encodeURIComponent(saved.productName)); const actual = result.products.find(p => p._id === saved.productId); if (actual) setProduct(actual); } window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const locked = Boolean(busy) || jobRunning || Boolean(post && post.status !== 'draft');
  const canPublish = images.length > 0 && caption.trim() && selected.length > 0 && (kind === 'photos' || (post?.videoStatus === 'ready' && post?.videoUrl));
  return <div className="social-publisher"><div className="social-section-title"><div><h2>Make your next post</h2><p>Start with a product. Give it your voice. Share it with your audience.</p></div>{product && <button onClick={() => { setProduct(null); setPost(null); setCaption(''); setImages([]); }} disabled={Boolean(busy)}><Plus size={16} /> New draft</button>}</div>
    {!product ? <section className="social-panel social-start-post"><span className="social-start-icon"><Sparkles size={30} /></span><h3>Your catalogue, ready for the spotlight.</h3><p>Product photos, name, price and shopping link are brought into your draft automatically.</p><button className="social-primary" onClick={() => setPicker(true)}><Plus size={17} /> Choose a product</button><div><span><Image size={16} /> Photo & carousel posts</span><span><Video size={16} /> Product video maker</span></div></section> : <div className="social-compose-grid"><section className="social-panel social-editor"><div className="social-product-summary"><img src={product.images[0]} alt="" /><div><small>FEATURED PRODUCT</small><h3>{product.name}</h3><strong>{money(product.price)}</strong></div><button aria-label="Choose another product" onClick={() => setPicker(true)} disabled={locked}><RefreshCw size={17} /></button></div><div className="social-format"><button className={kind === 'photos' ? 'is-active' : ''} disabled={locked} onClick={() => setKind('photos')}><Image size={18} /> Photos / carousel</button><button className={kind === 'reel' ? 'is-active' : ''} disabled={locked} onClick={() => setKind('reel')}><Video size={18} /> Product reel</button></div>
      <label className="social-field-title">Choose photos <small>{images.length}/6 selected · first selected is the cover</small></label><div className="social-photo-picker">{product.images.map(url => <button key={url} className={images.includes(url) ? 'is-selected' : ''} aria-label={`${images.includes(url) ? 'Deselect' : 'Select'} product photo ${product.images.indexOf(url) + 1}`} aria-pressed={images.includes(url)} disabled={locked || (!images.includes(url) && images.length >= 6)} onClick={() => setImages(previous => previous.includes(url) ? previous.filter(i => i !== url) : [...previous, url])}><img src={url} alt="" /><span>{images.includes(url) ? images.indexOf(url) + 1 : '+'}</span></button>)}</div>
      <label className="social-field-title" htmlFor="social-caption">Your caption <small>{caption.length}/2200</small></label><textarea id="social-caption" className="social-caption" rows={7} value={caption} maxLength={2200} disabled={locked} onChange={e => setCaption(e.target.value)} /><p className="social-footnote">Check the price and product details before publishing. Instagram caption links are displayed as text.</p>
      {kind === 'reel' && <div className="social-video-maker"><Video size={23} /><div><h3>Turn photos into a product video</h3><p>A vertical 9:16 video with 4 seconds per photo, product name and price. Review the finished preview before posting.</p>{post?.videoError && <p className="social-inline-warning">{post.videoError}</p>}<button disabled={locked || !images.length} onClick={() => act('video', async () => { const draft = await save(); const result = await client.post(`/posts/${draft._id}/video`, {}); setPost(result.post); onNotice('Video creation started. You can leave this page and return to the saved draft.'); })}>{pendingStatus(post?.videoStatus) ? <Spin /> : <Sparkles size={15} />}{post?.videoStatus === 'ready' ? 'Regenerate video' : pendingStatus(post?.videoStatus) ? 'Creating video…' : 'Create video preview'}</button></div></div>}
      <label className="social-field-title">Publish to <small>Select one or both channels</small></label><div className="social-destinations">{status.accounts.filter(a => a.capabilities.publish).map(a => <label key={a._id}><input type="checkbox" disabled={locked || a.status !== 'connected'} checked={selected.includes(a._id)} onChange={() => setSelected(previous => previous.includes(a._id) ? previous.filter(id => id !== a._id) : [...previous, a._id])} /><Brand provider={a.provider} size={19} /><span>{a.name}<small>{a.provider}</small></span></label>)}{!status.accounts.some(a => a.capabilities.publish) && <p>Connect an account with publishing access in Accounts. You can save this draft now.</p>}</div>
      <div className="social-editor-actions"><button disabled={locked || !images.length || !caption.trim()} onClick={() => act('save', async () => { await save(); onNotice('Draft saved. You can edit it whenever you need.'); })}>{busy === 'save' ? <Spin /> : null} Save draft</button><button className="social-primary" disabled={locked || !canPublish} onClick={() => act('review', async () => { const saved = await save(); if (kind === 'reel' && saved.videoStatus !== 'ready') { onNotice('The selected photos or product details changed. Regenerate and review the video first.'); return; } setConfirm(true); })}>{busy === 'review' ? <Spin /> : <Send size={16} />} Review & publish</button></div>
    </section><aside className="social-preview-column"><div className="social-section-title"><h3>Post preview</h3><span>{kind === 'reel' ? '9:16 video' : `${images.length} photo${images.length === 1 ? '' : 's'}`}</span></div><div className="social-post-preview"><header><span>S</span><div><strong>{status.store.name}</strong><small>Preview · your connected account</small></div><Instagram size={19} /></header>{kind === 'reel' && post?.videoUrl ? <video key={post.videoUrl} src={post.videoUrl} controls playsInline preload="metadata" aria-label="Product reel preview" /> : images[0] ? <div className="social-preview-image"><img src={images[0]} alt={product.name} />{kind === 'reel' && <span><Video size={17} /> Video preview appears here</span>}{kind === 'photos' && images.length > 1 && <b>1 / {images.length}</b>}</div> : <Empty Icon={Image} title="Choose your cover">Select a product photo to preview the post.</Empty>}<div className="social-preview-caption"><strong>{status.store.name}</strong><p>{caption}</p></div></div>{post?.videoUrl && <a className="social-download" href={post.videoUrl} download="product-reel.mp4" target="_blank" rel="noreferrer">Open / download video <ExternalLink size={14} /></a>}{post && <PostStatus post={post} />}</aside></div>}
    <div className="social-section-title social-history-heading"><h2>Drafts & publishing history</h2><button onClick={() => act('history', loadHistory)} disabled={Boolean(busy)}><RefreshCw size={15} /> Refresh</button></div>
    {!history.length ? <Empty Icon={Image} title="Your content starts here">Saved drafts and the result for every destination appear here.</Empty> : <div className="social-post-history">{history.map(item => <article key={item._id} className="social-panel social-history-card"><img src={item.images[0]} alt="" /><div><span className="social-eyebrow">{item.kind === 'reel' ? 'PRODUCT REEL' : 'PHOTO POST'} · {time(item.createdAt)}</span><h3>{item.productName}</h3><PostStatus post={item} /><div className="social-history-actions"><button disabled={Boolean(busy)} onClick={() => act('open', () => load(item))}>{item.status === 'draft' ? 'Open draft' : 'View details'} <ArrowRight size={14} /></button>{item.targets.some(t => t.status === 'failed') && !pendingStatus(item.status) && <button disabled={Boolean(busy)} onClick={() => act('retry', async () => { const result = await client.post(`/posts/${item._id}/retry`, {}); await load(result.post); await loadHistory(); onNotice('Retrying only destinations that reported a confirmed failure.'); })}>Retry failed destinations</button>}{item.status === 'draft' && !pendingStatus(item.videoStatus) && <button aria-label={`Delete draft ${item.productName}`} className="social-danger" onClick={() => setDeletePost(item)}><Trash2 size={15} /></button>}</div></div></article>)}</div>}
    {(historyMore || historyPage > 0) && <div className="social-pager"><button disabled={!historyPage} onClick={() => setHistoryPage(p => p - 1)}>Previous</button><span>{historyPage + 1}</span><button disabled={!historyMore} onClick={() => setHistoryPage(p => p + 1)}>Next</button></div>}
    {picker && <Modal title="Choose a product" onClose={() => setPicker(false)}><ProductPicker client={client} onSelect={choose} /></Modal>}
    {confirm && <Confirm title="Ready to share?" action="Publish now" busy={Boolean(busy)} onClose={() => setConfirm(false)} onConfirm={() => act('publish', async () => { const result = await client.post(`/posts/${post._id}/publish`, { connectionIds: selected }); setPost(result.post); setConfirm(false); await loadHistory(); onNotice('Post submitted. Each destination’s result will appear in publishing history.'); })}>Publish <strong>{product.name}</strong> to <strong>{status.accounts.filter(a => selected.includes(a._id)).map(a => `${a.name} (${a.provider})`).join(', ')}</strong>. This makes the content visible on those accounts. Meta processes each destination separately.</Confirm>}
    {deletePost && <Confirm title="Delete this draft?" action="Delete draft" busy={Boolean(busy)} onClose={() => setDeletePost(null)} onConfirm={() => act('delete', async () => { await client.delete('/posts/' + deletePost._id); if (post?._id === deletePost._id) { setPost(null); setProduct(null); } setDeletePost(null); await loadHistory(); onNotice('Draft deleted.'); })}>The saved caption and photo selection will be removed. Your original product stays in the catalogue.</Confirm>}
  </div>;
}

function PostStatus({ post }) { return <div className="social-post-status"><span className={`social-status ${post.status}`}>{pendingStatus(post.status) && <Spin />}{post.status === 'review' ? 'Check on Meta' : post.status}</span>{pendingStatus(post.videoStatus) && <small><Spin /> Creating video</small>}{post.videoError && <p className="social-inline-warning">{post.videoError}</p>}{post.targets?.map(t => <div key={t.connectionId}><Brand provider={t.provider} size={15} /><span>{t.name} · <strong>{t.status === 'unknown' ? 'Check on Meta' : t.status}</strong>{t.error && <small>{t.error}</small>}</span>{safeLink(t.permalink) && <a href={t.permalink} target="_blank" rel="noreferrer" aria-label={`Open post on ${t.provider}`}><ExternalLink size={15} /></a>}</div>)}</div>; }
function ProductPicker({ client, onSelect }) {
  const [search, setSearch] = useState(''), [page, setPage] = useState(0), [data, setData] = useState(null), [error, setError] = useState('');
  useEffect(() => { let live = true; const timer = setTimeout(() => { client.get(`/products?search=${encodeURIComponent(search)}&page=${page}`).then(result => { if (live) { setData(result); setError(''); } }).catch(e => { if (live) setError(e.message); }); }, 250); return () => { live = false; clearTimeout(timer); }; }, [client, search, page]);
  return <div className="social-product-picker"><label className="social-search"><Search size={17} /><input autoFocus placeholder="Search your catalogue" aria-label="Search products" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /></label>{error && <p role="alert">{error}</p>}{!data ? <div className="social-loading"><Spin /> Loading products…</div> : !data.products.length ? <Empty Icon={Image} title="No products found">Try another name or add an active product with photos to your catalogue.</Empty> : <div className="social-picker-grid">{data.products.map(p => <button key={p._id} disabled={!p.images.length} onClick={() => onSelect(p)}><img src={p.images[0]} alt="" /><strong>{p.name}</strong><span>{money(p.price)}</span><small>{p.images.length ? `${p.images.length} photos` : 'Add product photos first'}</small></button>)}</div>}<div className="social-pager"><button disabled={!page} onClick={() => setPage(p => p - 1)}>Previous</button><span>{page + 1}</span><button disabled={!data?.hasMore} onClick={() => setPage(p => p + 1)}>Next</button></div></div>;
}
function Modal({ title, children, onClose, locked = false }) {
  const ref = useRef(null);
  useEffect(() => {
    const previous = document.activeElement, overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; ref.current?.focus();
    const keydown = e => { if (e.key === 'Escape' && !locked) onClose(); if (e.key === 'Tab') { const items = ref.current.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),textarea:not(:disabled),select:not(:disabled),[tabindex="0"]'); if (!items.length) { e.preventDefault(); return; } const first = items[0], last = items[items.length - 1]; if (e.shiftKey && (document.activeElement === first || document.activeElement === ref.current)) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } } };
    document.addEventListener('keydown', keydown); return () => { document.body.style.overflow = overflow; document.removeEventListener('keydown', keydown); previous?.focus?.(); };
  }, [locked, onClose]);
  return <div className="social-modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget && !locked) onClose(); }}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className="social-modal"><header><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose} disabled={locked}><X size={20} /></button></header>{children}</section></div>;
}
function Confirm({ title, children, action, busy, onClose, onConfirm }) { return <Modal title={title} onClose={onClose} locked={busy}><p className="social-confirm-copy">{children}</p><footer className="social-confirm-actions"><button onClick={onClose} disabled={busy}>Cancel</button><button className="social-primary" onClick={onConfirm} disabled={busy}>{busy && <Spin />}{action}</button></footer></Modal>; }
